load_path: "" # only used when separately evaluating a pretrained model
eval: true
batch_size: 64
num_workers: 4
n_eval: 20
eval_every: 5
max_steps: 600
use_mp: false # multiprocessing does not work for the CUDA version on the cluster
num_procs: 1
save_sim_states: false
